import React, { useState } from 'react';
import { Card, Badge } from '../components/ui';
import { KnowledgeDoc, AppState } from '../types';
import { Search, FileText, Video, Download, Check, Loader2 } from 'lucide-react';
import { jsPDF } from "jspdf";
import { t } from '../utils/i18n';

interface KnowledgeBaseProps {
    docs: KnowledgeDoc[];
    appState?: AppState;
    lang: 'en' | 'ar' | 'zh' | 'ko'; 
    addToast?: (message: string, type: 'success' | 'error' | 'info' | 'warning') => void;
}

export const KnowledgeBaseView: React.FC<KnowledgeBaseProps> = ({ docs, lang, addToast }) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [activeCategory, setActiveCategory] = useState('All');
    const [downloadingId, setDownloadingId] = useState<string | null>(null);
    const [downloadedIds, setDownloadedIds] = useState<Set<string>>(new Set());
    
    // Correct categories based on mockData.ts (Manuals, Guides, Forms, Compliance)
    const categories = ['All', 'Manuals', 'Compliance', 'Guides', 'Forms'];

    const filteredDocs = docs.filter(d => {
        const matchesSearch = d.title.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesCategory = activeCategory === 'All' || d.category === activeCategory;
        const isNotSoftware = d.category !== 'Software'; 
        return matchesSearch && matchesCategory && isNotSoftware;
    });

    const handleDownload = async (doc: KnowledgeDoc) => {
        setDownloadingId(doc.id);
        
        // Simulate network delay
        await new Promise(resolve => setTimeout(resolve, 1500));

        try {
            // Generate a real dummy PDF file on the fly
            const pdf = new jsPDF();
            pdf.setFontSize(22);
            pdf.text(doc.title, 20, 20);
            
            pdf.setFontSize(16);
            pdf.text(`Category: ${doc.category}`, 20, 40);
            pdf.text(`Version: ${doc.lastUpdated}`, 20, 50);
            
            pdf.setFontSize(12);
            pdf.text("This document is a placeholder for demonstration purposes.", 20, 70);
            pdf.text("In a production environment, this would be the actual file content.", 20, 80);
            
            pdf.setLineWidth(0.5);
            pdf.line(20, 90, 190, 90);
            
            pdf.setFontSize(10);
            pdf.setTextColor(150);
            pdf.text("Generated by LaSoil SCADA System", 20, 280);

            pdf.save(`${doc.title.replace(/\s+/g, '_')}.pdf`);
            
            setDownloadedIds(prev => new Set(prev).add(doc.id));
            
            if (addToast) {
                addToast(`Downloaded ${doc.title} successfully.`, 'success');
            }
        } catch (error) {
            console.error("Download failed", error);
            if (addToast) {
                addToast("Download failed. Please try again.", 'error');
            }
        } finally {
            setDownloadingId(null);
        }
    };

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white">{t('docLibrary', lang)}</h2>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">{t('docSubtitle', lang)}</p>
                </div>
                <div className="relative w-full md:w-auto">
                    <Search className={`absolute top-2.5 text-slate-500 ${lang === 'ar' ? 'right-3' : 'left-3'}`} size={16} />
                    <input 
                        type="text" 
                        placeholder={t('searchDocs', lang)} 
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className={`bg-white dark:bg-scada-800 border border-slate-200 dark:border-scada-600 rounded-full py-2 text-sm text-slate-900 dark:text-white focus:border-scada-accent outline-none w-full md:w-64 ${lang === 'ar' ? 'pr-9 pl-4' : 'pl-9 pr-4'}`}
                    />
                </div>
            </div>

            {/* Categories */}
            <div className="flex gap-2 overflow-x-auto pb-2 custom-scrollbar">
                 {categories.map(cat => (
                     <button 
                        key={cat} 
                        onClick={() => setActiveCategory(cat)}
                        className={`px-4 py-2 rounded-lg text-sm transition-colors whitespace-nowrap ${
                            activeCategory === cat 
                            ? 'bg-scada-accent text-white font-bold shadow-md' 
                            : 'bg-white dark:bg-scada-800 hover:bg-slate-100 dark:hover:bg-scada-700 border border-slate-200 dark:border-scada-600 text-slate-600 dark:text-slate-300'
                        }`}
                     >
                         {/* Map category names to translation keys like 'cat_manuals' */}
                         {t(`cat_${cat.toLowerCase()}` as any, lang)}
                     </button>
                 ))}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {filteredDocs.length > 0 ? filteredDocs.map(doc => (
                    <Card key={doc.id} className="hover:border-scada-accent transition-colors cursor-pointer group hover:bg-slate-50 dark:hover:bg-scada-800/80">
                        <div className="flex items-start justify-between mb-4">
                            <div className={`p-3 rounded-lg ${doc.type === 'Video' ? 'bg-red-500/10 text-red-500 dark:text-red-400' : 'bg-blue-500/10 text-blue-500 dark:text-blue-400'}`}>
                                {doc.type === 'Video' ? <Video size={24} /> : <FileText size={24} />}
                            </div>
                            <Badge variant="neutral">{doc.category}</Badge>
                        </div>
                        <h3 className="font-bold text-slate-800 dark:text-slate-200 mb-2 group-hover:text-scada-accent transition-colors line-clamp-2 min-h-[3rem]">{doc.title}</h3>
                        <div className="flex justify-between items-center text-xs text-slate-500 mt-4 pt-4 border-t border-slate-100 dark:border-scada-700/50">
                            <span>{doc.size} • {doc.lastUpdated}</span>
                            
                            <button 
                                onClick={(e) => { e.stopPropagation(); handleDownload(doc); }}
                                disabled={downloadingId === doc.id}
                                className={`flex items-center gap-1 transition-colors font-bold ${
                                    downloadedIds.has(doc.id) 
                                    ? 'text-emerald-500' 
                                    : downloadingId === doc.id 
                                    ? 'text-slate-400' 
                                    : 'hover:text-scada-accent text-slate-400'
                                }`}
                            >
                                {downloadingId === doc.id ? (
                                    <><Loader2 size={14} className="animate-spin" /> {t('saving', lang)}</>
                                ) : downloadedIds.has(doc.id) ? (
                                    <><Check size={14} /> {t('saved', lang)}</>
                                ) : (
                                    <><Download size={14} /> {t('download', lang)}</>
                                )}
                            </button>
                        </div>
                    </Card>
                )) : (
                    <div className="col-span-full py-12 text-center text-slate-500 italic bg-white dark:bg-scada-800 rounded-xl border border-dashed border-slate-200 dark:border-scada-700">
                        {t('noResults', lang)} "{searchTerm}"
                    </div>
                )}
            </div>
        </div>
    );
};